project:
  type: website


# several branches can be specified here
branches:
  - branch: "release-2603"     # change this to the release branch
    output-dir: "2603"         # change this to year and month of the course instance

website:
  title: "Kursledarutbildning Steg 2"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - schedule.qmd
      - course_material.qmd
      - step2_syllabus.qmd
      - licence.qmd
      - text: "Kursledarprogram"
        href: https://wcs-umea.github.io/kursledarprogram/2025-2026/
  #    
  navbar:
    background: "#4A7263"
    logo: "img/wcsumea-logo.png"
  favicon: "img/wcsumea-logo.png"
  body-footer: footer.html
  body-header: banner.html


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
