---
title: "Information"
date: today
---

::: {.callout-warning icon=false}

## Om

**Organisatör:** 	                West Coast Swing Umeå  
**Datum:**	   	                    7 - 8 mars  
**Var:**		 			        Umeå    

:::

## Kursbeskrivning

Kursen går igenom de grundläggande kunskaperna som krävs för att på egen hand kunna hålla Steg 2-kurser inom WCS. Kursen går igenom de turer och tekniker som kan läras ut på en sådan kurs, samt hur man bäst lägger upp sin kurs.

Denna kurs är en del av [Kursledarprogrammet i WCS 2025-2026](https://wcs-umea.github.io/kursledarprogram/2025-2026/).

## Kursmål
Efter avslutad kurs ska eleven ha de kunskaper och verktyg för att kunna planera och hålla:

- Fortsättningskurs Steg 2


## Lärandemål

Efter avslutad utbildning ska deltagarna kunna:

- Demonstrera turerna enligt syllabus med korrekt timing och grundläggande teknik
- Förklara hur turerna på Steg 2 relaterar till de grundläggande turerna
- Använda föreslagen metodik för att lära ut turerna enligt kursplan Steg 2
- Selektera användbar feedback från deltagarna för att förbättra kursen
- Utvärdera och ge feedback på andra kursledare när det efterfrågas

