---
title: "Kursplanering Steg 2"
format:
  html: 
    toc: true
    theme: cosmo
  custom-pdfs-typst:
    keep-typ: true
format-links: false
course: "Kursledarutbildning Steg 2"
datetag: "Mars 2026"
footer: "West Coast Swing Umeås kursledarprogram 2025-2026"
---


## Kurslängd

Följande kursplanering är anpassad till en veckokurs som är 1 timme gånger 8 tillfällen. Vid längre/kortare kurser, samt helgkurser, kan innehållet behöva anpassas.

[Ladda ner kursplanering som PDF](step2_syllabus.pdf){target="_blank"}

## Mål

Målet med fortsättningskurs Steg 2 är att deltagarna ska få solida grunder och korrekt teknik.


## Lärandemål

Efter avslutad kurs ska deltagarna kunna:

- Utföra turerna i syllabus
- Dansa med korrekt timing
- Demonstrera bra frame utan arm lead
- Visa bra stretch och kompression


## Turer

Följande turer passar att lära ut på en Fortsättningskurs Steg 2. Beroende på antal gånger, samt hur gruppen är, kan detta behöva justeras något.


| Left side variations  |  Whip variations  | Right side variations  |
|-----------------------|-------------------|------------------------|
| Roll-in-roll-out      | Whip med inside/outside turn | Double outside turn |
| Slingshot             | Reversed whip     | Cut off/Hip catch |



## Tekniska koncept

Följande tekniska koncept är lämpliga att ta upp på en nybörjarkurs.

|             |                 | 
|-------------|-----------------|
| Keep momentum  | Få följarna att fortsätta rörelsen bakåt/framåt utan att stanna sig själva |
| Snurrteknik    | Spotting, prep, korta steg |
| Body lead | Få till frame så pass att förarna inte använder biceps |

: {tbl-colwidths="[25,75]"}


## Kursplanering

::: {.callout-warning icon=false}

## 
Se till att läsa de pedagogiska ramverken som diskuterades i kursutbildning Steg 1, då de inte alltid kommer nämnas explicit i texten, utan alltid ska användas. Visa, Pröva, Instruera, Öva bör användas för alla nya turer som lärs ut.

:::

### Tillfälle 1

**Fokus teknik:** Frame och momentum  
**Fokus turer:** Repetition och slingshot

#### Introduktion (~5 min)

Börja alltid med att introducera er själva och hälsa alla välkomna. Praktisk information såsom nödutgångar, eventuella avbrott i kursen, etc, tas upp innan ni kör igång och dansar. Då deltagarna kan ha lite olika bakgrund på en Steg 2 kurs (vissa kommer direkt från en Steg 1 kurs, vissa har haft ett längre uppehåll, och vissa kanske har gått den förut), är det bra att fråga lite om deltagarnas bakgrund, så att du som kursledare får en bättre överblick över nivån. Eventuellt kan du behöva anpassa kursen lite efter gruppens erfarenhet.

#### Repetition (~15-20 min)

Beroende på om kursen är en direkt fortsättning på Steg 1, och nivån i gruppen, kan repetitionen behöva förlängas eller förkortas. Syftet med repetitionen är att få alla kursdeltagara på samma sida innan ni börjar med nya turer. Visa snabbt de olika turerna från Steg 1, och låt deltagarna dansa till musik. Observera gruppen och se vad de har problem med och gå igenom detta mer i detalj.

#### Frame, body lead och momentum (~15 min)

Demonstrera hur deltagarna kan hålla axlarna på plats, utan att spänna biceps. Gör gärna om övningen Pass the follower, som beskrivs i Steg 1 materialet. Följarna får där lära sig att fortsätta momentum tills de blir redirected, och förarna får lära sig att använda kroppsförning. Efter övningen, låt deltagarna dansa tillsammans, håll det till left side pass, under arm och sugar push. Gå gärna runt och hjälp deltagarna.

#### Slingshot (~20 min)

En slingshot kan göras med några olika timings. Här fokuserar vi i första hand på den enklaste, med endast gå-gå steg. Visa, Pröva, Instruera, Öva gäller fortfarande. För en mer detaljerad instruktion till turen:

- Föraren söker följarens vänstra hand tidigt (innan 2)
- Det är förarens kroppsposition och viktförflyttning som ger förning, inte armar. Många förare kommer att använda armarna mer än nödvändigt. Poängtera att det är föraren som rör sig i motsatt håll från följaren som ger förningen i denna tur. 
- Frame är väldigt viktigt i denna tur, se till att händerna inte hamnar för högt
- Det ska vara ungefär lika mycket stretch i båda sidor
- Följaren måste fortsätta momentum tills det tar stopp. Många följare stannar för tidigt, eller fortsätter rörelsen med överkroppen endast och blir då tunga
- Föraren måste lyfta vänster arm för att indikera att följaren ska gå ut ur slingshoten

<br>

### Tillfälle 2

**Fokus teknik:** Connection när kroppen  
**Fokus turer:** Cut off/Hip catch  

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Nämn frame och momemtum, och gå igenom slingshot mer i detalj. 

#### Cut off/Hip catch (~25 min)

Även i en cut off finns det olika timings som föraren kan föra, men här fokuserar vi på den med endast gå-gå timing då den är enklast. Cut off passar bra att lära ut efter slingshot, då de liknar varandra, men är på olika sidor av föraren. Några viktiga punkter att tänka på i en cut off:

- Föraren startar förningen som i en under arm, men sätter fram höger hand för att connecta med följaren
- Förarens högra hand ska fånga upp följaren innan 3, och placeras strax under bröstkorgen på följarens högra sida. Trots att namnet hip catch ofta används om denna tur så ska handen inte placeras på höften
- Även i en cut off är det att föraren rör sig i motsatt riktning som följaren som skapar förningen, inte armarna
- Det är handen närmast följarens center som är ansvarig för förningen. Det betyder att det är förarens högra hand som för ut följaren från cut offen, inte den vänstra. Många förare drar för mycket med vänster
- Ta gärna lite mer tid här och prata om att förningen kommer från den hand som är närmast följarens center. Andra exempel är i en whip på 3&4
- När följaren känner connection i sidan så ska hen aktivt söka det connection. Samma här, många följare lutar med överkroppen istället för att gå med sidan. Om de får så mycket utrymme att de inte kan söka connection utan att tippa, så be dem ta ett steg till, hellre än att tippa överkroppen

#### Träning på Slingshot och Cut off (~10 min)

Låt deltagarna dansa och växla mellan slingshot och cut off. Gå gärna runt och hjälp deltagarna om ni ser något som kan förbättras. 

<br>

### Tillfälle 3

**Fokus teknik:** Snurrteknik  
**Fokus turer:** Whip med inside turn

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Gå igenom både slingshot och cut off. Slingshoten kan ni gå igenom ganska snabbt, men poängtera likheterna med cut offen. För cut off kan ni gå igenom den lite grundligare. Fråga om deltagarna har några frågor om dessa turer.

#### Träna whipteknik (~10 min)

Fokus på detta tillfälle och nästa kommer att vara varianter på whipar, därför passar det här bra med att jobba mer med tekniken i en whip. Följande är de tekniska detaljer som gicks igenom på Steg 1:

- Föraren öppnar upp sin fram något innan ettan, så att följaren får en naturlig “prep” innan steget, vilket får henne att rotera automatiskt
- Föraren bör fånga upp följarens rygg så snart som möjligt, för att kunna “släppa ut och dra in” på steg 3&4
- Följaren måste fortsätta momentum bakåt tills hen får en redirect
- På steg 4 ska följaren ha höger fot fram, men inte än ha lagt över vikten, vikten kommer på &et efteråt
- Förare ska inte heller ha lagt över vikten på 4an, utan viktförflyttningen sker på &et efteråt. Många förare är alldeles för snabba att lägga över vikten, och kan då inte längre föra ut följaren ordentligt
- Stanna på 4an ett par gånger för att inspektera positionerna som förare och följare har
- Så fort handen connectar med ryggen så är det den förningspunkt som gäller, då den är närmare följarens center, den andra handen för ej ut, utan rotationen och förningen ut kommer från förarens rotation och frame
- Förare har en tendens att pusha ut följaren på 5&6 med sin vänsterarm. För att undervika detta kan deltagarna träna på att släppa den andra handen så fort de connectat i ryggen

Lägg speciell fokus på att följarna fortsätter sitt momentum in i 3&4, och låter föraren redirecta dem. Föraren här måste ha bra frame, och använda sin egen kropp för redirecten. Gå gärna runt i gruppen, och tid finns även dansa med dem, för att kunna korrigera om ni ser något som inte stämmer.

#### Whip med inside turn (~25 min)

Ge en mer detaljerad instruktion till turen enligt nedan. Låt deltagarna stanna på 4, och gå igenom turen därifrån.

- På 4an måste följaren fortfarande ha connection bakåt, hen har fortfarande inte lagt över vikten på höger. Det här är det vanligaste misstaget bland nybörjare, och det som måste fungera för att kunna utföra en inside turn
- På 4an måste föraren indikera att hen vill göra en inside rotation, för att preppa på 5an
- Följaren måste också hålla tillbaka på 5an när hen preppar, liknande som 2an i in left side turn
- Föraren ger först riktning och sedan rotation. Följaren ska gå fram på 5an, sedan rotera
- Vanligaste misstagen är att följaren inte håller tillbaka och söker connection i ryggen, och att föraren stressar rotationen innan följaren har tagit steget framåt

<br>

### Tillfälle 4

**Fokus teknik:** Snurrteknik  
**Fokus turer:** Whip med outside turn

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Gå igenom tekniken i en vanlig whip, och koppla den samman med repetition av whip med inside turn (varför det är viktigt att följarna väntar på 4an och söker connection i ryggen).

#### Snurrteknik (~10 min)

De tekniska detaljer inom snurrteknik som behövs på Steg 2 är egentligen samma som för Steg 1. Bra snurrar tar lång tid att få till, så detta är ytterligare ett tillfälle för dem att träna på samma sak som i Steg 1.

Spotting: låt deltagaren fokusera blicken på en punkt rakt fram. Låt dem sakta rotera på stället tills de måste vrida huvudet för att åter kunna fokusera blicken på samma punkt
Prep: snurra ett varv där prep från överkroppen används
Små steg: Samma snurr som ovan där de också ska tänka på små steg i snurren, för att hålla balansen bättre

Här kan ni även lägga till att snurra 2-3 varv färdandes framåt, då detta kommer att användas i kommande turer.

#### Whip med outside turn (~25 min)

I Steg 2 kommer vi endast lära ut en whip med en enkel outside turn, inte double outside turn, då den är betydligt svårare. Ge en mer detaljerad instruktion till turen enligt nedan. Låt deltagarna stanna på 4, och gå igenom turen därifrån.


- Viktigt att följaren inte lägger över vikten på 4an utan på &et efter
- Föraren indikerar en outside turn genom att sätta upp vänster hand och peka fingrarna åt vänster
- Förningen för rotationen kommer från förarens höger, och sker genom förarens viktförflyttning, inte genom att trycka med vänsterhanden. Det här är ett vanligt misstag många nya förare gör
- Öva med att endast använda förningspunkten närmast följarens center, och låt förarna släppa sin vänsterhand helt. På det här sättet tränar de på att kroppsföra rotationen
- Föraren måste först föra fram följaren på hens högerfot, innan föraren kan initiera rotationen
- Rotationen sker på gå gå steget under 5, 6. Många stressar och roterar snabbare än de behöver

<br>

### Tillfälle 5

**Fokus teknik:** Preps  
**Fokus turer:** Reversed whip

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Repetera både whip med inside och outside turn, med fokus på följaren söker connection i ryggen och föraren för med connection point som är närmast följarens center.

#### Reversed whip (~20 min)

Ge en mer detaljerad instruktion till turen enligt nedan, visa likheterna med en vanlig left side turn.

- Föraren preppar som för en vanlig left side turn, men placerar sig på vänster sida av slotten istället för höger
- Liknande som i en free spin släpper föraren handen och låter följaren snurra fritt
- Föraren indikerar tidigt (2an) att det är en reversed whip och att hen tänkt fånga upp följaren med connection på ryggen
- Så fort följaren känner connection på ryggen är det denna connection hen ska följa, fortfarande med momentum i slottens riktning
- Förarens steg blir här liknande en början av en under arm

#### Träna whipvarianter (~15 min)

Låt deltagarna träna på de olika whipvarianterna de nu kan. Gå runt i gruppen och hjälp till om ni ser de har problem. Ser ni att de flesta klarar av de olika varianterna kan ni också visa och låta de prova att kombinera reversed whip med inside/outside turns. 

<br>

### Tillfälle 6

**Fokus teknik:**   
**Fokus turer:** Roll in roll out

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Repetera whipvarianterna, med mer fokus på reversed whip. Fråga deltagarna om de har några frågor gällande de olika varianterna.

#### Roll in roll out (~20 min)

En roll in roll out kan göras i några olika handfattningar, men här går vi igenom höger i vänster-handfattningen först. Ge en mer detaljerad instruktion till turen enligt nedan:

- Introducera en roll in roll out som en free spin där föraren "glömmer att släppa taget"
- Följaren roterar in tills det tar stopp (roterar in mot föraren så mycket som möjligt), se till att de håller sin frame (höger) hög nog för att glida över den connectade armen, annars fastnar de
- Föraren måste vara placerade väldigt nära följaren, något före följaren
- Följaren får inte lägga över sin vikt på 4an, innan föraren för hen 
- Föraren för ut följaren genom att lägga över sin egen vikt på (4) & som då resulterar i att följaren lägger över sin vikt
- Ingen annan förning behövs, då momentumet fram för följaren och det faktum att hens arm är connectad med föraren som står kvar, kommer få följaren att rotera upp
- Viktigt att föraren inte försöker dra följaren in i en rotation med armen, då det kan skada axlarna på följaren

Som träning kan man förlänga turen när följaren är inroterad på 4an, och lägga till gå-gå steg innan man låter följaren rotera ut. Det förhindrar att följarna roterar ut av sig själva innan de blir förda.

#### Roll in roll out höger i höger (~15 min)

En andra enkel variant av en roll in roll out är att göra den höger i höger. Föraren roterar då in följaren och placerar sin högerhand på följarens axel. Några detaljer:

- Följaren måste fortfarande rotera in tills det tar stopp
- Föraren måste placera sin hand på följarens axel. Många placerar den på nacken, vilket blir väldigt obehagligt när de försöker föra ut genom att trycka
- Förningen ut sker fortfarande genom viktförflyttningen för föraren

<br>

### Tillfälle 7

**Fokus teknik:**   
**Fokus turer:** Double outside turn

#### Uppvärmning (~5 min)

Låt deltagarna dansa själva för att värma upp. Deltagare som kommer lite sent till kursen har då en chans att hoppa in utan att missa något.

#### Repetition (~20 min)

Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid. Repetera de två roll in roll out varianterna.

#### Double outside turn




### Tillfälle 8





::: {.callout-warning icon=false}

## 
Upplägget i efterföljande tillfällen är detsamma som ovan, men i texten kommer vi endast fokusera på de unika detaljerna för varje tur och koncept

:::

